### ISSUE TITLE
Error in compiling project

### ISSUE THREAD

**Issue by murliswami** [Gabriellavoura/Mqtt-and-Sim800-900#1]
In file included from ...\Arduino\libraries\sim800\sim800Client.h:6:0,

                 from ...\Arduino\libraries\sim800\sim800.cpp:21:

...\Arduino\libraries\sim800\sim800.h:14:24: error: 'Serial1' was not declared in this scope

 #define HARDWARESERIAL Serial1

                        ^

...\Arduino\libraries\sim800\sim800.cpp:27:28: note: in expansion of macro 'HARDWARESERIAL'

   HardwareSerial *modem = &HARDWARESERIAL;

                            ^

exit status 1
Error compiling for board Arduino Nano.

PS: i am beginner in Ardunio plz suggest me

**Comment by Gabriellavoura** [comment]
Try to add HardwareSerial.h on your sketch.

`#include "HardwareSerial.h`

See this [Topic](https://github.com/espressif/arduino-esp32/issues/407) for more info.
