### ISSUE TITLE
fatal error: Time.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by lwh456789** [Gabriellavoura/Mqtt-and-Sim800-900#5]
为什么会出现这种情况，该怎么解决
fatal error: Time.h: No such file or directory
compilation terminated.

**Comment by lwh456789** [comment]
D:\Arduino\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -ID:\Arduino\hardware\arduino\avr\cores\arduino -ID:\Arduino\hardware\arduino\avr\variants\mega C:\Users\ADMINI~1\AppData\Local\Temp\build789388500709334239.tmp\mqtt_basic_pub_and_sub.cpp -o C:\Users\ADMINI~1\AppData\Local\Temp\build789388500709334239.tmp\mqtt_basic_pub_and_sub.cpp.o

**Comment by Gabriellavoura** [comment]
Hi, make sure that you have installed all the dependencies, like time.h from Arduino: https://playground.arduino.cc/Code/Time/

https://github.com/PaulStoffregen/Time

Be attentive to the hierarchy of folders when installing the dependencies.

Unzip all folders in your Arduino libraries folder, then set in the "tools" menu -> board 2560 option.

try the sketch in "example" folder.

Please,  if possible write in English, hope i helped you. 

> 
> 
> 为什么会出现这种情况，该怎么解决
> fatal error: Time.h: No such file or directory
> compilation terminated.

**Comment by lwh456789** [comment]
I replaced the original time.h with the new one that you provided me, but the original problem still appeared after compiling, and # include <Time. h >; delete, the problem after compilation is 
`fatal error: sim800Client.h: No such file or directory
compilation terminated.`

**Comment by lwh456789** [comment]
`#include <Time.h>
#include <sim800Client.h>
#include <PubSubClientHotlog.h>
#include <TimeAlarms.h>`

**Comment by lwh456789** [comment]
I wonder if the problem is the Arduino version. Mine is 1.6.3

**Comment by Gabriellavoura** [comment]
> 
> 
> I wonder if the problem is the Arduino version. Mine is 1.6.3

This look like a problem with the Arduino installation or compiler, just to verify, you must have this folder organization:

windows:
C:\Documents\Arduino\libraries\ < paste here the sim800, TimeAlarms, Time-Master, PubSub >

and

C:\Program Files (x86)\Arduino\libraries\  < paste here the sim800, TimeAlarms, Time-Master, PubSub >

![Screenshot (169)](https://user-images.githubusercontent.com/15681084/79094255-4e5dec80-7d2d-11ea-9e78-2dca6b8c507e.png)

I have tested to your Arduino version(1.6.3) and the sketch runs normally

What is your operational system?

**Comment by lwh456789** [comment]
win7 64

**Comment by lwh456789** [comment]
I'm using the program our friend here provided[https://github.com/Gabriellavoura/Mqtt-and-Sim800-900/tree/master/GPRS%20with%20MQTT%20for%20Sim800and900/Example/mqtt_basic_pub_and_sub](url)

**Comment by Gabriellavoura** [comment]
> 
> 
> I'm using the program our friend here provided[https://github.com/Gabriellavoura/Mqtt-and-Sim800-900/tree/master/GPRS%20with%20MQTT%20for%20Sim800and900/Example/mqtt_basic_pub_and_sub](url)

Ok, please verify if in your Arduino IDE this is showing:

![Screenshot (170)](https://user-images.githubusercontent.com/15681084/79095193-26bc5380-7d30-11ea-8941-7b1614f71017.png)
![Screenshot (171)](https://user-images.githubusercontent.com/15681084/79095195-2754ea00-7d30-11ea-97f7-ab6fce45af81.png)

You must have this, if not probably you installation of Arduino IDE is wrong

**Comment by lwh456789** [comment]
![IMG_8241](https://user-images.githubusercontent.com/63505637/79095731-c3610e80-7d8d-11ea-99cf-800cd10ac222.JPG)
![IMG_8242](https://user-images.githubusercontent.com/63505637/79095749-cfe56700-7d8d-11ea-894f-51ce43e6d87b.JPG)
![IMG_8243](https://user-images.githubusercontent.com/63505637/79095795-f3a8ad00-7d8d-11ea-9628-7d1fd548289b.JPG)

**Comment by lwh456789** [comment]
Can you compile it successfully

**Comment by Gabriellavoura** [comment]
I have made a downgrade to your version of Arduino IDE and i tried to reproduce your environment here. But the sketch works fine.

as you can see here, the sketch has success on compile:
![Screenshot (173)](https://user-images.githubusercontent.com/15681084/79096389-6fc1d700-7d33-11ea-9f91-2c77f89b237c.png)


Maybe is something with the Encoding or character conversion of UTF-8 to UTF-32?

> 
> 
> Can you compile it successfully?

**Comment by lwh456789** [comment]
Maybe I should try downloading the Arduino again

**Comment by Gabriellavoura** [comment]
> 
> 
> Maybe I should try downloading the Arduino again

Please try rename #include <Time.h>

to #include <TimeLib.h>

Searching here for a solution, i found that some win versions ignores the CamelCase notation, and cause conflict with time.h from C with Time.h from Arduino.

**Comment by lwh456789** [comment]
I've now re-downloaded the latest version of Arduino, and when I re-added libraries, it said it was invalid

**Comment by lwh456789** [comment]
![捕获](https://user-images.githubusercontent.com/63505637/79099235-4ab28000-7d96-11ea-9037-744306d90c35.JPG)

**Comment by Gabriellavoura** [comment]
>  it was invalid

This error is because the new version does not accept space in libraries name, just copy the content of zip file to your libraries folder in your documents like that:

![Screenshot (168)](https://user-images.githubusercontent.com/15681084/79099230-1610db00-7d3a-11ea-9754-73c3331cc06d.png)


Then open the sketch on example folder.

**Comment by lwh456789** [comment]
what should I do?

**Comment by lwh456789** [comment]
I've already added this, but the file is not shown in the example

**Comment by Gabriellavoura** [comment]
> 
> 
> I've already added this, but the file is not shown in the example

After put just the content of "GPRS with MQTT for Sim800and900" on your documents/Arduino/libraries/
Open the sketch manually, on IDE Arduino go to File -> Open - > Examples -> Mqtt_basic_pub_and_sub -> mqtt_basic_pub_and_sub.ino

**Comment by Gabriellavoura** [comment]
Please make sure that you paste Just the content of <GPRS with MQTT for Sim800and900> folder in your libraries:

![Screenshot (175)](https://user-images.githubusercontent.com/15681084/79100368-b405a500-7d3c-11ea-9d95-913e876b41af.png)

If you done that correctly you will have:

![Screenshot (176)](https://user-images.githubusercontent.com/15681084/79100520-1bbbf000-7d3d-11ea-9efd-6810e9b44c32.png)

**Comment by lwh456789** [comment]
That's exactly what I did, but only four other folders appear in the Example, and the Example folder doesn't appear

**Comment by lwh456789** [comment]
What are the common reasons for invalid libraries

**Comment by Gabriellavoura** [comment]
> 
> 
> That's exactly what I did, but only four other folders appear in the Example, and the Example folder doesn't appear

Try opening the sketch manually.

> 
> 
> What are the common reasons for invalid libraries

Wrong paths 😢 . That is strange, because i have done the same things here in my computer, and that is ok.

**Comment by Gabriellavoura** [comment]
> 
> 
> ![捕获](https://user-images.githubusercontent.com/63505637/79099235-4ab28000-7d96-11ea-9037-744306d90c35.JPG)

In this print, the path is wrong, because the folders are inside a "Mqtt-and-Sim800-900-master"
 folder.

**Comment by Gabriellavoura** [comment]
> 
> 
> That's exactly what I did, but only four other folders appear in the Example, and the Example folder doesn't appear

After change, always restart your Arduino IDE. Don’t forget this, as it doesn’t automatically detect changes in the file architecture.

**Comment by lwh456789** [comment]
Thank you, my friend. I've compiled it. Thank you for your guidance

**Comment by Gabriellavoura** [comment]
> Thank you, my friend. I've compiled it. Thank you for your guidance

I will work to update this project soon as possible, now I'm going to sleep, is 6 Am here in Brazil.

If you have any issue please leave a commt.

Happy for you, You are welcome!  😄
